"""empty message

Revision ID: 16b70bb4ff5b
Revises: 93681ea8c577
Create Date: 2024-05-02 15:55:20.418281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16b70bb4ff5b'
down_revision = '93681ea8c577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_timeline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timeline_translate', sa.JSON(), nullable=True))

    with op.batch_alter_table('client_visa_programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visa_program_translate', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_visa_programs', schema=None) as batch_op:
        batch_op.drop_column('visa_program_translate')

    with op.batch_alter_table('client_timeline', schema=None) as batch_op:
        batch_op.drop_column('timeline_translate')

    # ### end Alembic commands ###
