"""empty message

Revision ID: 3e422e8e34e9
Revises: 742c6ddc234b
Create Date: 2024-04-26 01:54:27.502360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e422e8e34e9'
down_revision = '742c6ddc234b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('investment_capital_available_range',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('investment_capital_available_range',
               existing_type=sa.String(length=100),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###
