"""empty message

Revision ID: 6ae1bb549739
Revises: fc0bd1e2cbde
Create Date: 2024-04-25 20:48:36.326091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ae1bb549739'
down_revision = 'fc0bd1e2cbde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('preferred_climate_type',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=100)),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='array_to_json(preferred_climate_type)')
        batch_op.alter_column('preferred_language',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=100)),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='array_to_json(preferred_language)')
        batch_op.alter_column('preferred_living_cost_range',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='array_to_json(preferred_living_cost_range)')
        batch_op.alter_column('investment_capital_available_range',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='array_to_json(investment_capital_available_range)')
        batch_op.alter_column('language_ability',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=100)),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='array_to_json(language_ability)')

    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.alter_column('dominant_language',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=100)),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='array_to_json(dominant_language)')
        batch_op.alter_column('in_demand_occupations',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=100)),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='array_to_json(in_demand_occupations)')
        batch_op.alter_column('living_cost',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='array_to_json(living_cost)')
        batch_op.alter_column('housing_cost_range',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='array_to_json(housing_cost_range)')
        batch_op.alter_column('land_use_types',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=100)),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='array_to_json(land_use_types)')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.alter_column('land_use_types',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR(length=100)),
               existing_nullable=True)
        batch_op.alter_column('housing_cost_range',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               existing_nullable=True)
        batch_op.alter_column('living_cost',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               existing_nullable=True)
        batch_op.alter_column('in_demand_occupations',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR(length=100)),
               existing_nullable=True)
        batch_op.alter_column('dominant_language',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR(length=100)),
               existing_nullable=True)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('language_ability',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR(length=100)),
               existing_nullable=True)
        batch_op.alter_column('investment_capital_available_range',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               existing_nullable=True)
        batch_op.alter_column('preferred_living_cost_range',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               existing_nullable=True)
        batch_op.alter_column('preferred_language',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR(length=100)),
               existing_nullable=True)
        batch_op.alter_column('preferred_climate_type',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR(length=100)),
               existing_nullable=True)

    # ### end Alembic commands ###
