"""empty message

Revision ID: 70432aa901c6
Revises: bc4c1eff6ed2
Create Date: 2024-04-28 19:35:07.471225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70432aa901c6'
down_revision = 'bc4c1eff6ed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visa_program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_id', sa.Integer()))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('photo', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visa_program', schema=None) as batch_op:
        batch_op.drop_column('photo')
        batch_op.drop_column('country')
        batch_op.drop_column('doc_id')

    # ### end Alembic commands ###
