"""empty message

Revision ID: 7267a426f8ab
Revises: 6ae1bb549739
Create Date: 2024-04-25 21:37:16.168499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7267a426f8ab'
down_revision = '6ae1bb549739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_industry', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('preferred_industry', sa.String(length=100), nullable=True))
        batch_op.drop_constraint('client_preferred_industry_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('client_work_industry_id_fkey', type_='foreignkey')
        batch_op.drop_column('preferred_industry_id')
        batch_op.drop_column('work_industry_id')

    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.add_column(sa.Column('climate_type', sa.String(length=100), nullable=True))
        batch_op.drop_constraint('destination_climate_type_id_fkey', type_='foreignkey')
        batch_op.drop_column('climate_type_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.add_column(sa.Column('climate_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('destination_climate_type_id_fkey', 'climate_type', ['climate_type_id'], ['id'])
        batch_op.drop_column('climate_type')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_industry_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('preferred_industry_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('client_work_industry_id_fkey', 'industry_type', ['work_industry_id'], ['id'])
        batch_op.create_foreign_key('client_preferred_industry_id_fkey', 'industry_type', ['preferred_industry_id'], ['id'])
        batch_op.drop_column('preferred_industry')
        batch_op.drop_column('work_industry')

    # ### end Alembic commands ###
