"""empty message

Revision ID: 93681ea8c577
Revises: db5372e37dd2
Create Date: 2024-04-30 00:26:10.305991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93681ea8c577'
down_revision = 'db5372e37dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=True),
    sa.Column('timeline', sa.JSON(), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_timeline')
    # ### end Alembic commands ###
