"""empty message

Revision ID: a006e7280b19
Revises: 3091b7afa3d5
Create Date: 2024-05-17 18:12:50.724111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a006e7280b19'
down_revision = '3091b7afa3d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visa_program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visa_program', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
