"""empty message

Revision ID: bc4c1eff6ed2
Revises: 3e422e8e34e9
Create Date: 2024-04-26 01:55:56.534293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc4c1eff6ed2'
down_revision = '3e422e8e34e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('preferred_living_cost_range',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('preferred_living_cost_range',
               existing_type=sa.String(length=100),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###
