"""empty message

Revision ID: d407715a6acd
Revises: 
Create Date: 2024-04-20 01:50:37.071730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd407715a6acd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=True),
    sa.Column('roles', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('preferred_climate_type', sa.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('preferred_language', sa.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('current_country_of_residence', sa.Integer(), nullable=True),
    sa.Column('citizenship_country', sa.Integer(), nullable=False),
    sa.Column('education_type', sa.String(length=100), nullable=True),
    sa.Column('education_level', sa.String(length=250), nullable=True),
    sa.Column('preferred_living_cost_range', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('years_of_work_experience', sa.Integer(), nullable=True),
    sa.Column('work_industry_id', sa.Integer(), nullable=True),
    sa.Column('investment_capital_available_range', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('marital_status', sa.String(length=100), nullable=True),
    sa.Column('number_of_dependant_accompanying', sa.Integer(), nullable=True),
    sa.Column('is_entrepreneur', sa.Boolean(), nullable=True),
    sa.Column('military_service_status', sa.String(length=100), nullable=True),
    sa.Column('has_criminal_record', sa.Boolean(), nullable=True),
    sa.Column('language_ability', sa.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('preferred_industry_id', sa.Integer(), nullable=True),
    sa.Column('health_status', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['preferred_industry_id'], ['industry_type.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_industry_id'], ['industry_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=250), nullable=False),
    sa.Column('born_date', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('roles', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('user_profile')
    op.drop_table('client')
    op.drop_table('users')
    # ### end Alembic commands ###
