"""empty message

Revision ID: fc0bd1e2cbde
Revises: a736e01fa9e9
Create Date: 2024-04-25 20:35:42.193041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc0bd1e2cbde'
down_revision = 'a736e01fa9e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('current_country_of_residence',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('citizenship_country',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.alter_column('country',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.alter_column('country',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('citizenship_country',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('current_country_of_residence',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
